### ISSUE TITLE
reporter-ureport fails due to HTTP 500 error code

### ISSUE THREAD

**Issue by genodeftest** [abrt/retrace-server#118]
Quite often when I try to report a crash using abrt, it fails in reporter-ureport with a HTTP 500 error code from https://retrace.fedoraproject.org/faf

**Comment by jfilak** [comment]
We have fixed a lot of problems on the server since you opened this issue. Do you still experience the issue?

**Comment by genodeftest** [comment]
I am seeing this issue again, unable to use gnome-abrt to report any issues to Fedora infrastructure after local analyzation, making `reporter-ureport` always fail.

report_EmergencyAnalysis also fails due to redirections.

**Comment by xsuchy** [comment]
@genodeftest do you see it now? It should be resolved now.

**Comment by genodeftest** [comment]
Luckily, I don't have a bug report at hand that fails. Can I trigger this?

**Comment by xsuchy** [comment]
@genodeftest will_crash from package will-crash

**Comment by genodeftest** [comment]
> @genodeftest will_crash from package will-crash

`[irony]`
I'd like to report a bug against that package that it does not crash ;)
`[/irony]`

Works fine now, see https://retrace.fedoraproject.org/faf/reports/bthash/f2c93d7e034f21d89daf6d3dd02e3a70e88826bb . Thanks for the fix!
