### ISSUE TITLE
Retrace server is unable to process package 'dnf-1.1.9-2.fc24.x86_64'.

### ISSUE THREAD

**Issue by danielkza** [abrt/retrace-server#122]
As the title says, I just hit a crash in DNF and the retrace server cannot handle processing the dump.

**Comment by jfilak** [comment]
Thank you for the report. The problem is that the coredump was generated by Python and not by dnf. This issue must be fixed in abrt-retrace-client [1]. Please, generate your core files locally until we fix this problem.

1: https://github.com/abrt/abrt/issues/993
