### ISSUE TITLE
Fails to handle recent Fedora 26 and Rawhide crashes

### ISSUE THREAD

**Issue by AdamWill** [abrt/retrace-server#151]
Lately I'm having trouble with using the retrace server for Fedora 26 and Rawhide crashes. Trying to use it (via gnome-abrt or report-cli, doesn't matter) I just get an error "Retrace server is unable to process package 'gnome-shell-3.24.1-1.fc26.x86_64'" (or similar). That package is a perfectly normal Fedora 26 package that went stable through Bodhi, nothing odd about it AFAICT.

**Comment by jfilak** [comment]
@xsuchy could you please look into this issue? Fedora users want retrace-server working:
https://lists.fedoraproject.org/archives/list/desktop@lists.fedoraproject.org/message/6F4ZQK4WAPJZQ66UHNAKKYUYOXYCA4ND/

**Comment by xsuchy** [comment]
This should be resolved now as we added F26 to retrace server.

**Comment by AdamWill** [comment]
How about Rawhide? I had the same issue with Rawhide crashes.

Can there be a procedure in place to ensure Rawhide tracing *always* works, and Branched releases are added to retrace-server at Branch point, without the need for people to notice it's missing and ask every cycle? The Branch point is on the schedule many weeks before it actually happens, and is always announced when it does happen; it shouldn't ever take anyone by surprise.

Thanks!

**Comment by xsuchy** [comment]
Rawhide should be fine. The problem was that we were fighting with disk space and we was unable to add new repo in branching time. This has been resolved and we should be able to add it at branching time next time.
