### ISSUE TITLE
Once again, server cannot handle Rawhide crashes

### ISSUE THREAD

**Issue by AdamWill** [abrt/retrace-server#163]
The retrace server once again doesn't seem able to handle Rawhide (F28, now) crashes.

**Comment by marusak** [comment]
Hi,
can you provide us with more information on this? (what package for example)
I tried retracing crash from rawhide (f28 version) and it works just fine.
Can you try again retracing the same problem of yours?

**Comment by AdamWill** [comment]
I think someone updated things shortly after I filed this, because it worked for me the other day too. It did not work when I filed this.

**Comment by marusak** [comment]
It is possible that packages were not yet downloaded.
