### ISSUE TITLE
Server can't handle many Rawhide packages ATM

### ISSUE THREAD

**Issue by AdamWill** [abrt/retrace-server#171]
I've tried to submit crashes for several different current Fedora Rawhide packages today, and the server claims it can't handle any of them. e.g. `gnome-initial-setup-3.26.0-2.fc28.x86_64` and `yelp-3.27.1-1.fc28`. Seems like something's wrong.

**Comment by xsuchy** [comment]
Hmm, I today 'yum upgrade' and new mock landed there. Can it be related....

**Comment by marusak** [comment]
I am pretty sure it is due to epoch version of those packages. It was fixed in https://github.com/abrt/retrace-server/commit/5c11ce5beabfdcff3bd4a15b4c88641522f26354 but yet not released.

**Comment by xsuchy** [comment]
The fix has been released looong time ago. Closing.
