### ISSUE TITLE
Failed to initialize security module

### ISSUE THREAD

**Issue by cmurf** [abrt/retrace-server#179]
Whenever I try to report a crash with any compose of Fedora 28 Workstation, abrt-cli always fails to upload the core dump due to Failed to initialize security module, so I have to do the debugging locally which for live media on a VM is pretty much a no go, it's just not worth it to download all the debug rpms for a throw away test.

liveuser@localhost-live ~]$ sudo abrt-cli list
id 8d814250320e51cb40a20d2f9a56fce11cd57e51
reason:         dnf_state_child_percentage_changed_cb(): packagekitd killed by SIGSEGV
time:           Tue 20 Mar 2018 10:15:07 PM EDT
cmdline:        /usr/libexec/packagekitd
package:        PackageKit-1.1.9-1.fc28
uid:            0 (root)
count:          1
Directory:      /var/spool/abrt/ccpp-2018-03-20-22:15:07.357965-2176
[liveuser@localhost-live ~]$ sudo abrt-cli report /var/spool/abrt/ccpp-2018-03-20-22:15:07.357965-2176
('report_uReport' completed successfully)
Ok to upload core dump? (It may contain sensitive data). If your answer is 'No', a stack trace will be generated locally. (It may download a huge amount of data). [y/N/f/e] y
Failed to initialize security module.
Do you want to generate a stack trace locally? (It may download a huge amount of data but reporting can't continue without stack trace). [y/N/f]

**Comment by marusak** [comment]
Thank you for the report. It is issue with ABRT not retrace server.
It has been fixed in https://github.com/abrt/abrt/commit/81f3f925f4853dadd78e7b1e5815f43cc7fe42ae

Simple workaround until the new version is available is to install nss-pem `sudo dnf install nss-pem`

**Comment by cmurf** [comment]
That fix is 21 days ago, and yet it's still not working in today's Fedora 28 compose, so somehow this fix is not actually in Fedora 28.

**Comment by marusak** [comment]
Because the latest F28 build was releases on 26. February
https://koji.fedoraproject.org/koji/buildinfo?buildID=1050226

**Comment by marusak** [comment]
New release https://bodhi.fedoraproject.org/updates/FEDORA-2018-bf6611b9f0
