### ISSUE TITLE
'fedora-29-x86_64 is not supported by the retrace server'

### ISSUE THREAD

**Issue by AdamWill** [abrt/retrace-server#221]
Per https://bugzilla.redhat.com/show_bug.cgi?id=1626851#c6 , it seems like the retrace server is not yet set up to handle Fedora 29. We need it to be. Thanks.

**Comment by xsuchy** [comment]
I just run PB which add cronjob to sync F29. Once it is synced it should work. I.e. tomorrow it should be fine. I will leave it open till I confirm it is done.

**Comment by kparal** [comment]
This particular error is gone, but no F29 package can still be traced. I get the "is this package part of official repositories?" error. Perhaps updates-testing is not enabled on that server?

**Comment by kparal** [comment]
Yeah, it seems that builds from updates-testing are not accepted, only from stable repos. Builds from stable repos all seem to fail with "No debuginfo found", but that's probably another issue (or perhaps simply debuginfo repos not enabled)?

**Comment by marusak** [comment]
Packages have been synced. It seems we miss a kernel debuginfos. I am investigating it now, why is that.

**Comment by marusak** [comment]
> It would be nice if either this system was made more sophisticated - you can use https://admin.fedoraproject.org/pkgdb/api/collections/ as a source of truth about current Fedora releases, for instance, we have several other systems that do that - or this was at least put on someone's TODO list - keep an eye on Fedora schedules and add new releases as they appear. It's kind of silly that nearly every cycle I have to notice this and file a ticket before you add the newly-branched release. :/

Releases are added automatically through PDC. Problem is with pulling packages. We need to insert a URLs for repositories, then pull all packages. And with every new build we need to pull that as well.
We try to automate this as much as possible, but its WIP.

**Comment by marusak** [comment]
it seems there is some bug as retracing acts strangely. Trying to find the real cause. In the meantime it should be possible to retrace, hopefully with a proper backtraces. Can someone please check this?

**Comment by kparal** [comment]
I have successfully retraced two crashes right now, so the problems might be gone, or they might happen just in certain circumstances.

**Comment by xsuchy** [comment]
This should be resolved now.
