### ISSUE TITLE
ftp.wsgi fails in async_ftp_list_dir on Python3 difference due to sorted() API change

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [abrt/retrace-server#225]
==> /var/log/httpd/ssl_error_log <==
[Fri Mar 15 09:22:55.919396 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39072]   File "/usr/share/retrace-server/ftp.wsgi", line 29, in async_ftp_list_dir
[Fri Mar 15 09:22:55.919398 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39072]     tasklist = sorted(rawtasklist, cmp=cmp_vmcores_first)
[Fri Mar 15 09:22:55.919413 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39072] TypeError: 'cmp' is an invalid keyword argument for this function
[Fri Mar 15 09:23:46.009640 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39078] mod_wsgi (pid=26209): Exception occurred processing WSGI script '/usr/share/retrace-server/ftp.wsgi'.
[Fri Mar 15 09:23:46.009795 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39078] Traceback (most recent call last):
[Fri Mar 15 09:23:46.009816 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39078]   File "/usr/share/retrace-server/ftp.wsgi", line 51, in application
[Fri Mar 15 09:23:46.009819 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39078]     output += async_ftp_list_dir(filterexp)
[Fri Mar 15 09:23:46.009830 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39078]   File "/usr/share/retrace-server/ftp.wsgi", line 29, in async_ftp_list_dir
[Fri Mar 15 09:23:46.009832 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39078]     tasklist = sorted(rawtasklist, cmp=cmp_vmcores_first)
[Fri Mar 15 09:23:46.009847 2019] [wsgi:error] [pid 26209:tid 139882156484352] [remote 10.10.121.77:39078] TypeError: 'cmp' is an invalid keyword argument for this function

https://docs.python.org/3/library/functions.html#sorted

https://docs.python.org/2/library/functions.html#sorted

**Comment by mkutlak** [comment]
Fixed in https://github.com/abrt/retrace-server/pull/228
