### ISSUE TITLE
Unable to Report Fedora 30 Beta Crash Reports

### ISSUE THREAD

**Issue by securerootd** [abrt/retrace-server#230]
--- Running report_uReport ---
('report_uReport' completed successfully)

--- Running analyze_CCpp ---
Ok to upload core dump? (It may contain sensitive data). If your answer is 'No', a stack trace will be generated locally. (It may download a huge amount of data). 'YES'
Querying server settings
Preparing an archive to upload
Uploading 1.4 MiB
Upload successful
Retrace job started
Preparing environment for backtrace generation
......
Generating backtrace
.
Retrace job failed
Retrace failed. Try again later and if the problem persists report this issue please.
    2019-04-08 16:33:12 Analyzing crash data
 2019-04-08 16:33:19 INFO:faf.Coredump2Packages:Executing eu-unstrip
INFO:faf.Coredump2Packages:Mapping build-ids into debuginfo packages
INFO:faf.Coredump2Packages:Getting binary packages from debuginfos

    2019-04-08 16:33:19 Preparing environment for backtrace generation
    2019-04-08 16:34:37 Generating backtrace
   2019-04-08 16:34:56 Running GDB failed

Do you want to generate a stack trace locally? (It may download a huge amount of data but reporting can't continue without stack trace). 'NO'
('analyze_CCpp' exited with 1)

--- Running report_EmergencyAnalysis ---
An archive will be created.
This archive is accessible only by ABRT developers.
Therefore if you try to open the produced web location you will not be able to see it.
Compressing data
Sending /var/tmp/ccpp-2019-04-08-22:02:53.509219-2978.tar.gz to https://retrace.fedoraproject.org
Successfully created https://retrace.fedoraproject.org/faf/dumpdirs/new/ccpp-2019-04-08-22:02:53.509219-2978.tar.gz

![image](https://user-images.githubusercontent.com/1446332/55741717-8e6bfe80-5a4b-11e9-8d08-103511d6f44b.png)

**Comment by securerootd** [comment]
![image](https://user-images.githubusercontent.com/1446332/55741769-b3607180-5a4b-11e9-8809-063ac8bcd638.png)

**Comment by mkutlak** [comment]
There was an issue on retrace-server(retrace.fedoraproject.org) that caused gdb to fail. This should be fixed now and retracing should work now. 

See #232

Closing.
