### ISSUE TITLE
fedora-30-ppc64le is not supported by retrace server

### ISSUE THREAD

**Issue by sztsian** [abrt/retrace-server#248]
@MingcongBai is using a Power 9 workstation. And when he want to report a bug by abrt, abrt shows

The release 'fedora-30-ppc64le' is not supported by the Retrace server.

As we support ppc64le, I think it makes sense to support ppc64le in retrace server.

I'm reporting this bug on his behalf, and if more info are needed, we can discuss in this issue.

**Comment by xsuchy** [comment]
Supporting another architecture means more use of storage. We are already driving on the edge. So sorry, without [Donation](https://fedoraproject.org/wiki/Donations) this is a no go. :(

**Comment by sztsian** [comment]
Ok, thanks. As long as this is a known issue this sounds resonable.
