### ISSUE TITLE
Retrace server cannot handle tildes in package versions

### ISSUE THREAD

**Issue by AdamWill** [abrt/retrace-server#250]
Since relatively recently, you're allowed to use tildes in Fedora package versions to indicate pre-releases (this is awful, but let's ignore that!) The retrace server, however, seems to choke on this:

    Querying server settings
    A server-side error occurred on 'https://retrace.fedoraproject.org'
    Unexpected HTTP response from server: 403
    Package NVR contains illegal characters
    ('analyze_RetraceServer' exited with 1)

this for a crash where `pkg_version` is `3.8.0~b4`.

**Comment by mkutlak** [comment]
Thank you @AdamWill , it should work now.
