### ISSUE TITLE
Move to python-requests-gssapi

### ISSUE THREAD

**Issue by ernestask** [abrt/retrace-server#263]
Context: https://fedoraproject.org/wiki/Changes/kerberos-in-python-modernization

**Comment by ernestask** [comment]
Due to https://github.com/pythongssapi/requests-gssapi/issues/12 and https://github.com/requests/requests-kerberos/issues/64, I think we should at least introduce a command-line option to disable mutual authentication.

Context for that: https://bugzilla.redhat.com/show_bug.cgi?id=1756367

**Comment by DaveWysochanskiRH** [comment]
I’m ok with that but can you please make it default disabled?  If not we will force a longer command line on everyone due to a known limitation as discussed in the python-requests-* bugs.

**Comment by ernestask** [comment]
That’s one thing I’m unsure about. If you have TLS on top the setup, mutual authentication is rather pointless, but then you also have https://github.com/pythongssapi/requests-gssapi#mutual-authentication stating that it’s rather pointless in most cases.
