### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [abrt/retrace-server#283]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by ernestask** [comment]
> * [mandatory] which branch is your development branch?

master

> * [mandatory] have you merged latest translation from Zanata and locked the project?

Yes and no. The project is owned by a developer who had left the team without giving anyone else access.

> * [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

None of them really fit, so not answering.

> * [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)

No.

> * [optional] do you need us to activate any specific checks? (this is a setting per component [3])

Not at the moment.

> * [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

I don’t know how it works, even. Yes?

**Comment by Jibec** [comment]
Thanks for your answers.

>> * [mandatory] have you merged latest translation from Zanata and
>> locked the project?
> 
> Yes and no. The project is owned by a developer who had left the team
> without giving anyone else access.

I understand that you merged the latest translations from Zanata in your 
repo, but can't lock it.
Please confirm.

Locking the project we can do easily, I asked our admin to do so.

**Comment by ernestask** [comment]
> I understand that you merged the latest translations from Zanata in your repo, but can't lock it. Please confirm.

That is precisely it.

**Comment by Jibec** [comment]
thank you,

I started configuration: https://translate.stg.fedoraproject.org/projects/abrt/retrace-server/#translations
please remove empty po files

**Comment by Jibec** [comment]
I commented each issue with required action.
Once done, finish the configuration will be easy.

I chosed the  GPL-2.0-or-later license by reading your repository

**Comment by ernestask** [comment]
> please remove empty po files

There are none, unless you mean those with zero translated strings.

> I chosed the GPL-2.0-or-later license by reading your repository

That’s the code license. For translations, I would rather have them be in the public domain, but that’s not a possibility.

**Comment by Jibec** [comment]
Discussion about translation license was opened on the Fedora translator 
mailing list: 
https://lists.fedoraproject.org/archives/list/trans@lists.fedoraproject.org/message/ZTWRA7FA25BJ7GRB6RFWWB7SQVZH6MUB/
So far, feedback isn't positive.

Would you like to reconsider this position or open the question to 
Fedora Legal mailing list?

**Comment by Jibec** [comment]
And yes, I meant the zero translated strings for all projects.

**Comment by ernestask** [comment]
> Would you like to reconsider this position or open the question to Fedora Legal mailing list?

My position is that of uncertainty. The question *needs* to be answered by Legal, especially if the translations are actually bound by the Fedora CLA.

**Comment by Jibec** [comment]
Could you then please open a thread on Fedora legal mailing list or would you prefer me to do it? Daniel also had a nice way of rephrasing it:
--
"is licensing translations under a more permissive license than
the effective license of the combined work acceptable or desirable"

To be clear, I think translations should be given the same license
as the code in general. Does that have to be a "MUST" or is "SHOULD"
acceptable ?
--

In the meanwhile, I'll configure your projects but will keep it read-only on Weblate.

My suggestion is to keep it simple: same license as code.
We'll only get conflicts to try to find another model if the reason to do different license so isn't clear.

Our goal: establish the best possible collaboration between upstream projects and contributors. The better you are as upstream, the better we are downstream for end users.

**Comment by ernestask** [comment]
Posted via the web UI, could not CC: https://lists.fedorahosted.org/archives/list/legal@lists.fedoraproject.org/thread/F436XTPUAYU4SE4IZDO52G22H2PQN5WC/

My goal is no longer to set a license of my choosing, but to actually figure this out and set out guidelines. I will only care as much as Legal does, so you’re free to go with the code license if there is no response after a reasonable amount of time.

**Comment by ernestask** [comment]
So, given the response on the list and the fact that Zanata doesn’t really state any information about licensing, I am going to assume that all translations we have consumed so far are under CC-BY-NC-SA-3.0, since that’s the default for content submitted under no explicit license. AIUI, translators are able to license their work explicitly, so this becomes even more complex.

The only question remains whether translations are considered content, but I don’t have any arguments against that.

**Comment by ernestask** [comment]
But, for austerity, I asked for clarification on the list about being able to assume that what we have is compatible with CC-BY-SA-3.0 without having knowledge of a contributor setting their own terms.

**Comment by Jibec** [comment]
configuration is done: 
https://translate.stg.fedoraproject.org/projects/abrt/retrace-server/


LINGUAS will be updated by Weblate

PO files will be updated by Weblate when POT is updated

Weblate will use Git Squash by author to limit the number of commits

I enabled language consistency between your components (if you add a 
language in one component, it will add it to all components)
