### ISSUE TITLE
retrace-server-task create <pathtofile> no longer works but throws "sequence item 0: expected str instance, PosixPath found"

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [abrt/retrace-server#326]
I'm getting the following error now 100% of the time on 831dc3e3d241:

    [2020-06-08 23:24:15] [I] Post-processing downloaded file
    [2020-06-08 23:24:15] [E] sequence item 0: expected str instance, PosixPath found

I have not tracked this down but maybe someone recognizes this after all the recent changes?

**Comment by ernestask** [comment]
Yeah, it’s all the pathlib madness.

**Comment by DaveWysochanskiRH** [comment]
Thanks!
