### ISSUE TITLE
retrace-server-task create throws "'str' object has no attribute 'name'`"

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [abrt/retrace-server#327]
After the latest change 766215c53f03 I get a bit further with "retrace-server-task create" but a new error is thrown and it still doesn't complete:

    [2020-06-09 07:17:57] [I] Post-processing downloaded file
    [2020-06-09 07:17:57] [I] Analyzing crash data
    [2020-06-09 07:17:57] [E] 'str' object has no attribute 'name'`

**Comment by ernestask** [comment]
@michalfabik, I would suggest going once or twice more through your changes.

**Comment by DaveWysochanskiRH** [comment]
Thanks!  There is a new problem now though - cannot find the file.

**Comment by ernestask** [comment]
Yeah, I saw that one as well, but I keep thinking it’s because I use it wrong.
