### ISSUE TITLE
retrace-server-task create fails with "Crash directory does not contain required file" even though file exists and is readable

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [abrt/retrace-server#329]
After b5a2bda4725b retrace-server-task create fails with:

    [2020-06-09 08:07:53] [I] Post-processing downloaded file
    [2020-06-09 08:07:53] [I] Analyzing crash data
    [2020-06-09 08:07:53] [E] Crash directory does not contain required file 'vmcore'

**Comment by ernestask** [comment]
Spoiler:
https://github.com/abrt/retrace-server/blob/b5a2bda4725bf5a002d0077d22b5e0f06faec608/src/retrace/retrace.py#L1695

There’s more breakage after this.

**Comment by ernestask** [comment]
https://github.com/abrt/retrace-server/blob/b5a2bda4725bf5a002d0077d22b5e0f06faec608/src/retrace/retrace.py#L1128

**Comment by ernestask** [comment]
https://github.com/abrt/retrace-server/blob/b5a2bda4725bf5a002d0077d22b5e0f06faec608/src/retrace/retrace.py#L1134

**Comment by ernestask** [comment]
If I may repeat myself: https://github.com/abrt/retrace-server/pull/310#issuecomment-608381441

All this either grows tests, gets fixed or gets reverted.
