### ISSUE TITLE
Users unable run retrace-server-worker --restart due to write permissions to /cores/retrace/repos/ 

### ISSUE THREAD

**Issue by DaveWysochanskiRH** [abrt/retrace-server#346]
We're had a problem for a while but it would be good to solve it.  Basically if a user has a vmcore with a custom kernel-debuginfo and they either don't know this or they forget and submit a vmcore to retrace-server the task will fail.  Then they copy the kernel-debuginfo into /cores/retrace/repos/download and use: retrace-server-worker --restart <taskid>.  This command fails though because the user cannot create a directory inside /cores/retrace/repos/kernel to extract the debuginfo and an error like this goes into the log:
~~~
[2020-06-28 19:59:43] [I] Searching for kernel-debuginfo package for 3.10.0-1127.el7.bz1400159.dbg5.x86_64
[2020-06-28 20:00:38] [E] prepare_debuginfo failed: Failed vmlinux caching from debuginfo at location: /cores/retrace/repos/kernel/x86_64/usr/lib/debug/lib/modules/3.10.0-1127.el7.bz1400159.dbg5.x86_64/vmlinux
~~~

After this point, there is one more error relating to the 'stats.db' file, in the _fail() method.  The stats.db file too is only writeable by retrace user so this fails:
~~~
[2020-06-28 20:00:38] [W] Failed to save crash statistics: attempt to write a readonly database
~~~

I am not sure exactly what approach to use to fix these problems.  If there was some way to submit these commands so that some 'retrace' owner task would pick them up (i.e. through httpd I guess) then these issues would disappear.  Failing that we could try some permissions tricks on the files / directories but I'm not sure that is a good approach.

**Comment by DaveWysochanskiRH** [comment]
Forgot to say - right now you'll only see this problem if you first apply https://github.com/abrt/retrace-server/pull/345

**Comment by ernestask** [comment]
We kinda sorta had a similar problem in ABRT itself and what we ended up doing was setting setgid on the binary and ensuring that the directories are group-writable.

**Comment by DaveWysochanskiRH** [comment]
Actually there are more problems with "retrace-server-worker --restart" than I thought.  I just saw another error:
~~~
[2020-06-29 12:58:14] [E] [Errno 13] Permission denied: '/cores/retrace/tasks/974590112/md5sum'
~~~
And there's no group write perms on that, understandably:
~~~
$ ls -lh /cores/retrace/tasks/974590112/md5sum
-rw-r--r-- 1 retrace my-retrace-group 166 Jun 29 12:34 /cores/retrace/tasks/974590112/md5sum
~~~

Probably the best approach is to investigate how we can restart a task similar to creating one, i.e. maybe retire "retrace-server-worker --restart" from the commandline by users, and only do "retrace-server-task restart <taskid>" or something like that
