### ISSUE TITLE
Error when cleaning up a retrace task

### ISSUE THREAD

**Issue by mgrabovsky** [abrt/retrace-server#381]
The following error (encountered on retrace.fp.org) was reported by @xsuchy:
```
$ sudo -u retrace retrace-server-worker --restart 112306597
Failed to set locale, defaulting to C.UTF-8
Traceback (most recent call last):
   File "/bin/retrace-server-worker", line 45, in <module>
     task.reset()
   File "/usr/lib/python3.6/site-packages/retrace/retrace.py", line 2570, in reset
     os.unlink(os.path.join(self._savedir, filename))
IsADirectoryError: [Errno 21] Is a directory: '/srv/retrace/tasks/112306597/log'
```

`tasks/NNNN/log` is a directory, so we need to delete the files one by one and only then remove the directory.

The only difference in the [current version](https://github.com/abrt/retrace-server/blob/93c9820/src/retrace/retrace.py#L1868) is that we're using pathlib now.

**Comment by DaveWysochanskiRH** [comment]
> IsADirectoryError: [Errno 21] Is a directory: '/srv/retrace/tasks/112306597/log'

How did 'log' get there in the first place?
