### ISSUE TITLE
Missing dependency on logrotate

### ISSUE THREAD

**Issue by mgrabovsky** [abrt/retrace-server#403]
[rpmlint](https://github.com/rpm-software-management/rpmlint) reports that retrace-server is missing a formal dependency on logrotate which should apparently be present due to the `/etc/logrotate.d/retrace-server` file.

**Comment by xsuchy** [comment]
We should not require it, but rather recommend it. But we should own `/etc/logrotate.d/`.

**Comment by mgrabovsky** [comment]
Indeed, [it can be](https://github.com/rpm-software-management/rpmlint/blob/c6b42fee4fd0534c7a7fa983f1e77bf5cf1ea2d2/rpmlint/checks/FilesCheck.py#L553-L555) either of `Requires`, `Recommends` or `Suggests`.

**Comment by mgrabovsky** [comment]
Closed by #405.
