### ISSUE TITLE
Retrace server does not support F34

### ISSUE THREAD

**Issue by AdamWill** [abrt/retrace-server#414]
Trying to report a crash from F34 at present just gives an error "The release 'fedora-34-x86_64' is not supported by the Retrace server." Can we please fix this? Also, it would be nice if this were done automatically or at least if someone remembered to do it manually at each branch point, so we don't have to keep reporting this every time a release branches...

**Comment by mgrabovsky** [comment]
Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1931345

**Comment by cmurf** [comment]
Downstream bug is proposed as a Fedora 34 release blocker. Blocker review on IRC in #fedora-blocker-review on 2021-03-01 17:00:00 UTC, it'd be nice to get an opinion from abrt/retrace server folks on this either in the meeting, here, or the downstream bug report.

**Comment by msrb** [comment]
@cmurf Hi there. This will be fixed: https://pagure.io/fedora-infra/ansible/pull-request/445#

**Comment by AdamWill** [comment]
so 34 is supported now, but it frequently seems to not have the debuginfo for recent packages. Is it not including updates-testing? updates-testing is enabled by default for Branched releases, so it really needs to pull in the debuginfo from updates-testing packages promptly.

**Comment by mgrabovsky** [comment]
Yeah, we're aware of the issue. We've been having trouble pulling new rpms from the repos (see #958), but we're close to resolving this.

**Comment by mgrabovsky** [comment]
This should be fixed now. You can now retrace Fedora 33 and 34 crashes on retrace.fp.org. Support for Rawhide is planned for next week.
