### ISSUE TITLE
F36 not supported?

### ISSUE THREAD

**Issue by kparal** [abrt/retrace-server#459]
Hello, I tried to upload a core dump from abrt today and the I received an immediate message "Retrace failed". Is it perhaps because F36 is still not supported? We'd really need to have it supported asap because of pre-release validation, thank you!

**Comment by mgrabovsky** [comment]
What was the exact error message? We had some issues the past three days that should be resolved as of about noon today.

**Comment by kparal** [comment]
There was no error message, just "Retrace failed" (even in the log). But you are right, the problem is gone now. I tried again and it processed the backtrace for some time, and spit out "low informational value" error. But that's a different error, so I'll close this ticket.
