### ISSUE TITLE
Fedora 37 not supported

### ISSUE THREAD

**Issue by kparal** [abrt/retrace-server#471]
Fedora 37 has been branched some time ago, please make it supported in retrace server, QA needs it! Thanks a lot.

![Screenshot_f37_2022-08-25_12:31:09](https://user-images.githubusercontent.com/755451/186642281-e825d2a7-2472-4fde-91bf-9b700f32bc5a.png)

**Comment by mgrabovsky** [comment]
Thanks for the report. You should now be able to retrace crashes from Fedora 37.
