### ISSUE TITLE
Enable user-space cores in task manager

### ISSUE THREAD

**Issue by mozeq** [abrt/retrace-server#60]
Opened '20121204T11:05:39' by mtoman as https://fedorahosted.org/abrt/ticket/901

The backend is ready, webUI probably needs big changes. The question is how to reliably distinguish between user-space core & vmcore.

**Comment by mbrysa** [comment]
Closed via https://github.com/abrt/retrace-server/commit/a42447538299e41ac56b32859ccd219f69df1503
