### ISSUE TITLE
use dnf instead of yum

### ISSUE THREAD

**Issue by MichaelMraka** [abrt/retrace-server#85]
Fedora moved from yum to dnf as a default package manager, please update your code.
See also https://bugzilla.redhat.com/show_bug.cgi?id=1156560.

**Comment by xsuchy** [comment]
See https://github.com/abrt/retrace-server/pull/97

**Comment by mkutlak** [comment]
Fixed in pull request -  https://github.com/abrt/retrace-server/pull/218
