### ISSUE TITLE
Broken links in notifications

### ISSUE THREAD

**Issue by ralphbean** [abrt/retrace-server#96]
Look at this example fedmsg notification from today:

https://apps.fedoraproject.org/datagrepper/id?id=2016-3311b7db-7639-4344-ac0b-592f6466babb&is_raw=true&size=extra-large

See the "url" field in there?  It has ``example.org`` as the domain, which is incorrect.  Perhaps the abrt server is misconfigured in production?

**Comment by jfilak** [comment]
Oops, http://retrace.fedoraproject.org/ is miss-configured. An automatic system upgrade restored the default values.

**Comment by jfilak** [comment]
@ralphbean  Is this issue fixed? We've updated the configuration files on the abrt server.

**Comment by ralphbean** [comment]
It looks like it is fixed, yes.  You can see the urls for FAF messages here:

https://apps.fedoraproject.org/datagrepper/raw?category=faf&delta=127800

Mouse over the left-most icon for each entry and click it, for an example (or click the 'JSON' link to see the payload).

Thanks!
